### ISSUE TITLE
3 vendors flagged as malicious (virustotal)

### ISSUE THREAD

**Issue by Maveee** [ShineAsNine/GfycatDownloader#1]
https://www.virustotal.com/gui/file/79dc921ab1c58e2241af66dbe60108489763e70e9999963ee00b9887a01b64d2\

Any idea why it's giving these results?

**Comment by ShineAsNine** [comment]
Probably because of [this](https://github.com/pyinstaller/pyinstaller/issues/6754#issuecomment-1100821249), but feel free to look through the code and clone and recompile it yourself if you still feel the exe is unsafe. Or if you don't want to do that I believe [gallery-dl](https://github.com/mikf/gallery-dl) just updated to allow Gfycat authentication.
